### ISSUE TITLE
Front end cleanup

### ISSUE THREAD

**Issue by kimwdavidson** [GetDKAN/data-catalog-frontend#20]
##Tasks
- [ ] remove all styled components
- [ ] replace with sass files 
- [ ] make it look finished

##Acceptance criteria
- [ ] Kim thinks it looks nice
